### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DHow2** [Panchovix/stable-diffusion-webui-reForge#212] opened 2024-12-23 17:42 UTC
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Both settings, enable Clip skip for SDXL and FP8 weight for SDXL won't work or change anything. It doesn't matter if I have Clip skip SDXL enabled or disabled, any other CLIP than 2 just outputs a plain grey picture.
Changes in FP8  weight also don't take effect. Used VRAM etc just stays the same and output image info also confirms no FP8 weight.
I tried using reforge again after some time (Had the same problem a month ago and just kept using normal 1111 instead and now reinstalled reForge and have the same issue.

### Steps to reproduce the problem

Go to settings and using "Clip skip SDXL" or "FP8 weight SDXL".
And/Or
Adding those settings to the Quicksettings list on the top of the page and then using it
will both not take effect.

### What should have happened?

Enabling CLIP for SDXL/
Using FP8 weights for SDXL

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-12-23-17-24.json](https://github.com/user-attachments/files/18231838/sysinfo-2024-12-23-17-24.json)

### Console logs

```Shell
venv "F:\ReForge\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.1.5-v1.10.1RC-latest-866-g82c17c39
Commit hash: 82c17c39e0a1aff991f897290d857a57a778b9ec
Launching Web UI with arguments: --cuda-stream --pin-shared-memory --cuda-malloc --ckpt-dir F:/WEBUI/stable-diffusion-webui/models/Stable-diffusion --hypernetwork-dir F:/WEBUI/stable-diffusion-webui/models/hypernetworks --embeddings-dir F:/WEBUI/stable-diffusion-webui/embeddings --lora-dir F:/WEBUI/stable-diffusion-webui/models/Lora --vae-dir F:/WEBUI/stable-diffusion-webui/models/VAE
Using cudaMallocAsync backend.
Total VRAM 12282 MB, total RAM 130162 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
F:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
F:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
ControlNet preprocessor location: F:\ReForge\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
F:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
[-] ADetailer initialized. version: 24.11.1, num models: 10
sd-webui-prompt-all-in-one background API service started successfully.
F:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
Loading model ebara_pony_1.bakedVAE.safetensors [b6ce8a2bf8] (1 of 1)
Loading weights [b6ce8a2bf8] from F:\WEBUI\stable-diffusion-webui\models\Stable-diffusion\ebara_pony_1.bakedVAE.safetensors
model_type EPS
UNet ADM Dimension 2816
2024-12-23 18:39:04,016 - ControlNet - INFO - ControlNet UI callback registered.
[ERROR]: Config states F:\ReForge\stable-diffusion-webui-reForge\config_states\civitai_subfolders.json, "created_at" does not exist
Running on local URL:  http://127.0.0.1:7860
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
F:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Loading VAE weights specified in settings: F:\WEBUI\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11041.624114990234
[Memory Management] Model Memory (MB) =  2144.3535232543945
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7873.27059173584
Moving model(s) has taken 0.26 seconds
Model ebara_pony_1.bakedVAE.safetensors [b6ce8a2bf8] loaded in 3.1s (load weights from disk: 0.1s, forge load real models: 2.1s, load VAE: 0.1s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.4s).

To create a public link, set `share=True` in `launch()`.
Startup time: 23.3s (prepare environment: 3.9s, import torch: 3.0s, import gradio: 0.6s, setup paths: 0.6s, initialize shared: 0.3s, other imports: 0.3s, load scripts: 4.2s, create ui: 1.6s, gradio launch: 2.6s, app_started_callback: 6.0s).
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  9037.596403121948
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3116.5099086761475
Moving model(s) has taken 0.69 seconds
 60%|██████████████████████████████████████████████▊                               | 18/30 [00:05<00:03,  3.14it/s]Applying NGMS at step 18: s_min_uncond = 0.6, sigma = 0.5131644606590271            | 18/30 [00:05<00:03,  3.18it/s]
 67%|████████████████████████████████████████████████████                          | 20/30 [00:06<00:02,  3.45it/s]Applying NGMS at step 20: s_min_uncond = 0.6, sigma = 0.39518624544143677           | 20/30 [00:05<00:02,  3.67it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 22/30 [00:06<00:02,  3.69it/s]Applying NGMS at step 22: s_min_uncond = 0.6, sigma = 0.2859876751899719            | 22/30 [00:06<00:02,  3.99it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 24/30 [00:07<00:01,  3.82it/s]Applying NGMS at step 24: s_min_uncond = 0.6, sigma = 0.1914280354976654            | 24/30 [00:06<00:01,  4.19it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 26/30 [00:07<00:01,  3.88it/s]Applying NGMS at step 26: s_min_uncond = 0.6, sigma = 0.1158723309636116███▋        | 26/30 [00:07<00:00,  4.28it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 28/30 [00:08<00:00,  3.88it/s]Applying NGMS at step 28: s_min_uncond = 0.6, sigma = 0.04635332524776459██████▊    | 28/30 [00:07<00:00,  4.26it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.40it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.34it/s]
To load target model SDXL██████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  4.33it/s]
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  4082.443904876709
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3058.443904876709
Moving model(s) has taken 0.02 seconds
 60%|██████████████████████████████████████████████▊                               | 18/30 [00:05<00:03,  3.16it/s]Applying NGMS at step 18: s_min_uncond = 0.6, sigma = 0.5131644606590271            | 18/30 [00:05<00:03,  3.21it/s]
 67%|████████████████████████████████████████████████████                          | 20/30 [00:06<00:02,  3.51it/s]Applying NGMS at step 20: s_min_uncond = 0.6, sigma = 0.39518624544143677           | 20/30 [00:05<00:02,  3.70it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 22/30 [00:06<00:02,  3.71it/s]Applying NGMS at step 22: s_min_uncond = 0.6, sigma = 0.2859876751899719            | 22/30 [00:06<00:01,  4.03it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 24/30 [00:07<00:01,  3.81it/s]Applying NGMS at step 24: s_min_uncond = 0.6, sigma = 0.1914280354976654            | 24/30 [00:06<00:01,  4.20it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 26/30 [00:07<00:01,  3.85it/s]Applying NGMS at step 26: s_min_uncond = 0.6, sigma = 0.1158723309636116███▋        | 26/30 [00:07<00:00,  4.28it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 28/30 [00:08<00:00,  3.84it/s]Applying NGMS at step 28: s_min_uncond = 0.6, sigma = 0.04635332524776459██████▊    | 28/30 [00:07<00:00,  4.29it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.47it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.35it/s]
To load target model SDXL██████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  4.26it/s]
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  4287.636451721191
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3263.6364517211914
Moving model(s) has taken 0.02 seconds
100%|██████████████████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.16it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.07it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.16it/s]
```

### Additional information

webui1111 works fine with all these settings.

**Comment by Panchovix** [comment] 2024-12-23 19:52
Closing as duplicate of https://github.com/Panchovix/stable-diffusion-webui-reForge/issues/118

**Closed by Panchovix** 2024-12-23 19:52 UTC
